#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把 anthropics/ClaudeForFoundationModels 同步成项目内的本地 Swift 包。

为什么不直接用 SPM 远程依赖：上游 Package.swift 声明 iOS 27 起，源码里也没有任何
@available 标注；而 App 部署目标是 iOS 26.0，Xcode 会直接拒绝链接。
最低版本不升（要保留 iOS 26 用户），于是把源码拷进 Packages/ 并做两处机械改动：

1. 本地 Package.swift 声明 iOS 26 起；
2. 给 ClaudeForFoundationModels 目标里每个顶层声明加
   @available(iOS 27.0, macOS 27.0, visionOS 27.0, watchOS 27.0, *)。
   App 侧本来就只在 `#available(iOS 27.0, *)` 分支里用它。

⚠️ 不能改用「给这个模块单独设 iOS 27 部署目标」之类的编译参数：那样对
FoundationModels iOS 27 符号的引用会变成强链接，静态链进 App 后 iOS 26 设备启动即崩。

Apache 2.0 要求被修改的文件带显著的修改说明，脚本会自动在每个改过的文件里加注释。

用法：
    python3 tools/vendor-claude-fm.py            # 同步默认版本（见 DEFAULT_REF）
    python3 tools/vendor-claude-fm.py 0.3.0      # 同步指定 tag
"""
import pathlib, re, shutil, subprocess, sys, tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEST = ROOT / "Packages" / "ClaudeForFoundationModels"
UPSTREAM = "https://github.com/anthropics/ClaudeForFoundationModels"
DEFAULT_REF = "0.2.2"

# 需要标注的目标。ClaudeAPI 不依赖 FoundationModels，原样拷贝即可。
ANNOTATED_TARGETS = {"ClaudeForFoundationModels"}
COPIED_TARGETS = ["ClaudeAPI", "ClaudeForFoundationModels"]

AVAILABILITY = "@available(iOS 27.0, macOS 27.0, visionOS 27.0, watchOS 27.0, *)"
NOTICE = (
    "// Modified for CashbackCounter: top-level declarations annotated with\n"
    f"// {AVAILABILITY}\n"
    "// so the package links into an iOS 26 deployment target. See VENDORED.md.\n"
)

MODIFIERS = r"(?:(?:public|private|fileprivate|internal|package|final|nonisolated|indirect)\s+)*"
DECL = re.compile(MODIFIERS + r"(?:struct|enum|class|actor|protocol|extension|func|typealias)\b")
# 顶层存储属性没法加 @available，碰到就让人来处理，而不是悄悄生成编译不过/会崩的代码
UNSUPPORTED = re.compile(MODIFIERS + r"(?:let|var)\b")
ATTRIBUTE_LINE = re.compile(r"@\w")

PACKAGE_SWIFT = """\
// swift-tools-version: 6.2
// Vendored copy of {upstream} — see VENDORED.md.
// Generated by tools/vendor-claude-fm.py; do not edit by hand.
//
// Upstream declares iOS 27 as the minimum platform. This copy declares iOS 26
// so the app (deployment target 26.0) can link it; every declaration in the
// ClaudeForFoundationModels target carries @available(iOS 27.0, ...) instead.
import PackageDescription

let package = Package(
  name: "ClaudeForFoundationModels",
  platforms: [
    .iOS("26.0"), .macOS("26.0"), .visionOS("26.0"), .watchOS("26.0"),
  ],
  products: [
    .library(name: "ClaudeForFoundationModels", targets: ["ClaudeForFoundationModels"])
  ],
  targets: [
    .target(name: "ClaudeAPI"),
    .target(name: "ClaudeForFoundationModels", dependencies: ["ClaudeAPI"]),
  ]
)
"""

VENDORED_MD = """\
# ClaudeForFoundationModels（内置副本）

- 上游：{upstream}
- 版本：`{ref}`（commit `{commit}`）
- 许可：Apache 2.0，见同目录 LICENSE

## 相对上游的改动

由 `tools/vendor-claude-fm.py` 机械生成，不要手改这里的源码——升级时重新跑脚本：

1. `Package.swift` 是本地版本：平台最低声明为 iOS 26，只保留两个库目标（去掉示例和测试）。
2. `Sources/ClaudeForFoundationModels/` 下每个顶层声明前加了
   `{availability}`，被改动的文件顶部带修改说明。

原因：App 部署目标是 iOS 26.0，而上游声明 iOS 27 起且源码没有 @available，
直接作为 SPM 依赖会被 Xcode 拒绝。App 侧只在 `#available(iOS 27.0, *)` 分支里使用它。
"""


def annotate(source: str, path: pathlib.Path) -> tuple[str, int]:
    lines = source.split("\n")
    out: list[str] = []
    count = 0
    attr_start = None  # 当前顶层属性行（如 @MainActor 单独成行）在 out 里的起点
    for line in lines:
        if UNSUPPORTED.match(line):
            sys.exit(f"✗ {path.name}: 顶层存储属性无法加 @available，需要人工处理：\n    {line}")
        if ATTRIBUTE_LINE.match(line) and not line.startswith("@available"):
            if attr_start is None:
                attr_start = len(out)
            out.append(line)
            continue
        if DECL.match(line):
            insert_at = attr_start if attr_start is not None else len(out)
            out.insert(insert_at, AVAILABILITY)
            count += 1
        attr_start = None
        out.append(line)
    text = "\n".join(out)
    if count:
        # 修改说明放在上游许可证头注释之后、第一行代码之前
        match = re.match(r"((?://[^\n]*\n)+\n?)", text)
        head = match.group(1) if match else ""
        rest = text[len(head):]
        text = (head.rstrip("\n") + "\n\n" if head else "") + NOTICE + "\n" + rest
    return text, count


def main() -> None:
    ref = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_REF
    with tempfile.TemporaryDirectory() as tmp:
        checkout = pathlib.Path(tmp) / "upstream"
        subprocess.run(
            ["git", "clone", "-q", "--depth", "1", "--branch", ref, UPSTREAM, str(checkout)],
            check=True,
        )
        commit = subprocess.run(
            ["git", "-C", str(checkout), "rev-parse", "HEAD"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()

        sources = DEST / "Sources"
        if sources.exists():
            shutil.rmtree(sources)
        DEST.mkdir(parents=True, exist_ok=True)

        total = 0
        for target in COPIED_TARGETS:
            src_dir = checkout / "Sources" / target
            dst_dir = sources / target
            dst_dir.mkdir(parents=True)
            for file in sorted(src_dir.glob("*.swift")):
                text = file.read_text(encoding="utf-8")
                if target in ANNOTATED_TARGETS:
                    text, count = annotate(text, file)
                    total += count
                (dst_dir / file.name).write_text(text, encoding="utf-8")

        shutil.copy(checkout / "LICENSE", DEST / "LICENSE")
        (DEST / "Package.swift").write_text(PACKAGE_SWIFT.format(upstream=UPSTREAM), encoding="utf-8")
        (DEST / "VENDORED.md").write_text(
            VENDORED_MD.format(upstream=UPSTREAM, ref=ref, commit=commit, availability=AVAILABILITY),
            encoding="utf-8",
        )

    print(f"✓ 已同步 {ref} ({commit[:7]}) → {DEST.relative_to(ROOT)}，共标注 {total} 处顶层声明")


if __name__ == "__main__":
    main()
