// swift-tools-version: 6.2
// Vendored copy of https://github.com/anthropics/ClaudeForFoundationModels — see VENDORED.md.
// Generated by tools/vendor-claude-fm.py; do not edit by hand.
//
// Upstream declares iOS 27 as the minimum platform. This copy declares iOS 26
// so the app (deployment target 26.0) can link it; every declaration in the
// ClaudeForFoundationModels target carries @available(iOS 27.0, ...) instead.
import PackageDescription

let package = Package(
  name: "ClaudeForFoundationModels",
  platforms: [
    .iOS("26.0"), .macOS("26.0"), .visionOS("26.0"), .watchOS("26.0"),
  ],
  products: [
    .library(name: "ClaudeForFoundationModels", targets: ["ClaudeForFoundationModels"])
  ],
  targets: [
    .target(name: "ClaudeAPI"),
    .target(name: "ClaudeForFoundationModels", dependencies: ["ClaudeAPI"]),
  ]
)
